const ONE_SECOND_IN_MS = 1000;
const ONE_MINUTE_IN_SECONDS = 60;
const FIFTEEN_MINUTES_IN_SECONDS = 15 * ONE_MINUTE_IN_SECONDS;

export const TIME_IN_MS = {
  FIFTEEN_MINUTES: FIFTEEN_MINUTES_IN_SECONDS * ONE_SECOND_IN_MS,
} as const;

export const APP_DEFAULTS = {
  PORT: 3000,
  NODE_ENV: 'development',
  RATE_LIMIT_WINDOW_MS: TIME_IN_MS.FIFTEEN_MINUTES,
  RATE_LIMIT_MAX_REQUESTS: 100,
  RATE_LIMIT_AUTH_MAX_REQUESTS: 5,
} as const;
